#API key/secret
consumer_key: 9g1lK6xnupRE17PS1wCiFlUmw
consumer_secret: xlywOsQb9B9vI5lhefETJhMmJ526CkDwhTJdrFnar9ExljknfV
#Access token/secret
access_token: 292715684-Wd6xzHXA28tf6E3XGjbQDPkpaVKvHPHfhrtMRjJd
access_token_secret: Y9dMGaEOhnDRgOV78YWQSlpde6CLeNeoCD5uvgRq0mEoP
